# Generated by Django 3.0.1 on 2020-01-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0002_auto_20200102_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, upload_to='packages'),
        ),
    ]
