# Generated by Django 3.0.1 on 2020-01-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0003_auto_20200102_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, max_length=32),
        ),
    ]
