# Generated by Django 3.0.1 on 2020-01-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0004_auto_20200102_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
