# Generated by Django 3.0.1 on 2020-01-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0005_theme_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Online Payment'), ('transfer', 'Bank Transfer')], default='online', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
