# Generated by Django 3.0.1 on 2020-01-03 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0006_auto_20200103_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cost',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
