# Generated by Django 3.0.1 on 2020-01-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0007_auto_20200103_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(),
        ),
    ]
