# Generated by Django 3.0.1 on 2020-01-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0008_auto_20200105_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_service_active',
            field=models.BooleanField(default=False),
        ),
    ]
