# Generated by Django 3.0.1 on 2020-01-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0010_auto_20200106_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.FloatField(null=True),
        ),
    ]
