# Generated by Django 3.0.1 on 2020-01-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0012_emailsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
