# Generated by Django 2.2.9 on 2020-01-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0014_blog_poll_polloptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
