# Generated by Django 2.2.9 on 2020-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0015_auto_20200113_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
