# Generated by Django 2.2.9 on 2020-01-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0017_auto_20200114_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_domain_owner',
            field=models.BooleanField(default=False),
        ),
    ]
