# Generated by Django 2.2.9 on 2020-01-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishr', '0018_order_is_domain_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
